name: Publish Package

on:
    workflow_dispatch:
    release:
        types: [created]

permissions:
  contents: read
  id-token: write  

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4'  # Specify the R version you need
      
      - name: Install libcurl on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev

      - name: Install R packages
        run: |
          Rscript -e 'install.packages("BiocManager")'
          Rscript -e 'BiocManager::install(c("WGCNA", "limma"))'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run tests
        run: |
          poetry run pytest -m 'not slow'
          poetry run pytest
      - name: Build package
        run: |
          poetry build
      - name: Publish to PyPI via Trusted Publisher
        uses: pypa/gh-action-pypi-publish@release/v1
