name: 'tests'  # Fast every-push testing

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: run tests
        uses: docker://freddsle/unpast:latest
        with:
          entrypoint: bash
          args: >
            -c "
            cd /github/workspace
            && python -m pytest unpast/tests -m 'not slow'
            && python -m pytest unpast/tests --durations=0
            "
