# action.yml
name: 'tests'

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.2'  # Specify the R version you need

      - name: Install R packages
        run: |
          R -e "install.packages('BiocManager')"
          R -e "BiocManager::install('WGCNA')"
          R -e "BiocManager::install('limma')"

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run tests
        run: |
          poetry run pytest -m 'not slow'
          poetry run pytest
